update: readme and config updation, Profile Name change
browserstack/testng-appium-app-browserstack pull request #25
Opened 2023-01-04 15:43 UTC by kamal-kaur04

2023-01-10 08:45 UTC, karanshah-browserstack approved these changes
LGTM

2023-01-10 08:53 UTC, karanshah-browserstack requested changes

2023-01-10 08:53 UTC, karanshah-browserstack commented on ios/testng-examples/browserstack.yml
>  projectName: TestNg Android Project
BrowserStack Samples. Let's keep it consistent for both products.

2023-01-10 08:53 UTC, karanshah-browserstack commented on android/testng-examples/browserstack.yml
>  projectName: TestNg Android Project
BrowserStack Samples. Let's keep it consistent for both products.

2023-01-10 15:30 UTC, avinash-bharti approved these changes

2023-01-12 09:22 UTC, karanshah-browserstack approved these changes

2023-01-12 09:42 UTC, avinash-bharti approved these changes

2023-01-12 10:53 UTC, merged